---
title: Dahlia Malkhi / PhD
description: Personal homepage of Dahlia Malkhi, Chief Research Officer at Chainlink Labs
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
# Outputting
permalink: /:categories/:title/
paginate: 15 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


include:
- ".htaccess"
- _pages
- files
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- CHANGELOG
- Capfile
- Gemfile
- Gruntfile.js
- LICENSE
- README
- Rakefile
- config
- gulpfile.js
- log
- node_modules
- package.json
- tmp
- vendor
keep_files:
- ".git"
- ".svn"

plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-redirect-from
- jekyll-include-cache

author:
  name: Dahlia Malkhi
  avatar: "/images/dahliabest.jpg"
  bio: Chief Research Officer of Chainlink Labs
  location: California
  employer: 
  pubmed: 
  googlescholar: http://scholar.google.com/citations?user=A_VZ7N0AAAAJ&hl=en
  email: 
  researchgate: 
  github: dahliamalkhi
  linkedin: dahlia-malkhi-8b836a5
  twitter: dahlia_malkhi
  wikipedia: 
  dblp: https://dblp.uni-trier.de/pers/m/Malkhi:Dahlia.html

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: false
    comments: 
    share: true
    related: true
    show_date: true
    classes: wide
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: true
    classes: wide
locale: en-US
title_separator: "-"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

url: https://dahliamalkhi.github.io
baseurl: ''
repository: dahliamalkhi/dahliamalkhi.github.io
teaser: 
breadcrumbs: false

#collections:
#  posts:
#    title: Posts
#    output: true

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


